FROM eduardodeoh/ubuntu_core:14.04_with_ansible
MAINTAINER eduardodeoh@gmail.com

#PRE-REQUISITES
RUN apt-get -y install git-core python-apt

RUN adduser --disabled-password --gecos "" deploy
ADD inventory /etc/ansible/hosts
ADD ./playbook-ruby.yml /tmp/playbook.yml
RUN ansible-galaxy install eduardodeoh.ruby
RUN ansible-playbook -vvvv /tmp/playbook.yml
